name: The Life of Brian
favicon: null
layout_spectrum: 0.3109
typography_spectrum: 0.4050179
title: Stories from my absolutely normal life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F1F5F8'
    - '#F9C7B4'
    - '#B4876E'
    - '#4B3930'
    - '#659ACF'
  brandStrength: 0.625
  lightness: 0.5234042
  saturation: 0.2003639
  rhythmicContrast: 0.6594982
purpose: []
