typography_spectrum: 0.4050179
color:
  saturation: 0.2003639
  brandStrength: 0.625
  lightness: 0.5913978
  brandColors:
    - '#F1F5F8'
    - '#F9C7B4'
    - '#B4876E'
    - '#4B3930'
    - '#659ACF'
  rhythmicContrast: 0.6594982
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
name: The Life of Brian
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The life of Brian
description: That's me!
purpose: []
